matrix:
  include:
    - language: python
      python: 3.5
      install:
        - pip install -r backend/requirements.txt
        - pip install pylint
        - pip install coverage
      before_script:
        - cd backend
      script:
        - coverage run --source backend -m unittest discover
      after_success:
        - coverage report
        - pylint backend

